HLK-substitutions:
  name: ble-presence-sensor
  friendly_name: BLE Presence Sensor

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/firmware/esphome-web/esp32c3.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

i2c:
  sda: 10
  scl: 9  

binary_sensor:
  - platform: gpio
    pin: 
      number: 1
      mode:
        input: true
        pullup: true
    name: "pir_state"
    id: pir_state
 
  - platform: gpio
    pin: 
      number: 2
      mode:
        input: true
        pullup: true
    device_class: presence
    name: "radar_state"
    id: radar_state
 
sensor: 
  - platform: bh1750
    name: "Light Sensor"
    address: 0x23
    update_interval: 60s

switch:
  - platform: gpio
    pin: 3
    name: "Light"        
